//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// Name der Ursprungsdatei:
// Erstellungsdatum: 5/5/2014 11:16:58 AM
namespace SilverlightContrib.Sample.SampleDataServices
{
    
    /// <summary>
    /// Es gibt keine Kommentare für SampleDataServiceContext im Schema.
    /// </summary>
    public partial class SampleDataServiceContext : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialisiert ein neues SampleDataServiceContext-Objekt.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public SampleDataServiceContext(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Da sich der Namespace, der für diesen Dienstverweis
        ///  in Visual Studio konfiguriert ist, von demjenigen unterscheidet, der in dem 
        /// Server-Schema angegeben ist, verwenden Sie Typemapper, um Zuordnungen zwischen den beiden vorzunehmen.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("SilverlightContrib.Sample.Web", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("SilverlightContrib.Sample.SampleDataServices", typeName.Substring(29)), false);
            }
            return null;
        }
        /// <summary>
        /// Da sich der Namespace, der für diesen Dienstverweis
        ///  in Visual Studio konfiguriert ist, von demjenigen unterscheidet, der in dem 
        /// Server-Schema angegeben ist, verwenden Sie Typemapper, um Zuordnungen zwischen den beiden vorzunehmen.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("SilverlightContrib.Sample.SampleDataServices", global::System.StringComparison.Ordinal))
            {
                return string.Concat("SilverlightContrib.Sample.Web.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// Es gibt keine Kommentare für Customers im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Customer> Customers
        {
            get
            {
                if ((this._Customers == null))
                {
                    this._Customers = base.CreateQuery<Customer>("Customers");
                }
                return this._Customers;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Customer> _Customers;
        /// <summary>
        /// Es gibt keine Kommentare für Customers im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCustomers(Customer customer)
        {
            base.AddObject("Customers", customer);
        }
    }
    /// <summary>
    /// Es gibt keine Kommentare für SilverlightContrib.Sample.Web.Customer im Schema.
    /// </summary>
    /// <KeyProperties>
    /// CustomerID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("CustomerID")]
    public partial class Customer
    {
        /// <summary>
        /// Erstellt ein neues Customer-Objekt.
        /// </summary>
        /// <param name="customerID">Anfangswert von CustomerID.</param>
        /// <param name="birthDate">Anfangswert von BirthDate.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Customer CreateCustomer(int customerID, global::System.DateTime birthDate)
        {
            Customer customer = new Customer();
            customer.CustomerID = customerID;
            customer.BirthDate = birthDate;
            return customer;
        }
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft CustomerID im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int CustomerID
        {
            get
            {
                return this._CustomerID;
            }
            set
            {
                this.OnCustomerIDChanging(value);
                this._CustomerID = value;
                this.OnCustomerIDChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _CustomerID;
        partial void OnCustomerIDChanging(int value);
        partial void OnCustomerIDChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft Name im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft BirthDate im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime BirthDate
        {
            get
            {
                return this._BirthDate;
            }
            set
            {
                this.OnBirthDateChanging(value);
                this._BirthDate = value;
                this.OnBirthDateChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _BirthDate;
        partial void OnBirthDateChanging(global::System.DateTime value);
        partial void OnBirthDateChanged();
    }
}
