//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilverlightContrib {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SilverlightContrib.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Conversion not supported ähnelt.
        /// </summary>
        public static string ExceptionConversionNotSupported {
            get {
                return ResourceManager.GetString("ExceptionConversionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Emf source cannot be re-used over multiple Emf controls ähnelt.
        /// </summary>
        public static string ExceptionEmfSourceReuse {
            get {
                return ResourceManager.GetString("ExceptionEmfSourceReuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die End of stream reached while expecting more data ähnelt.
        /// </summary>
        public static string ExceptionEndOfStream {
            get {
                return ResourceManager.GetString("ExceptionEndOfStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stream does not contain Enhanced Metafile data ähnelt.
        /// </summary>
        public static string ExceptionNoEmfStream {
            get {
                return ResourceManager.GetString("ExceptionNoEmfStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Length of string value {0} does not fit in range [{1}..{2}] ähnelt.
        /// </summary>
        public static string ExceptionStringLength {
            get {
                return ResourceManager.GetString("ExceptionStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enhanced Metafile function {0} not supported ähnelt.
        /// </summary>
        public static string MessageEmfFunctionNotSupported {
            get {
                return ResourceManager.GetString("MessageEmfFunctionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enhanced Metafile function {0:X} unknown ähnelt.
        /// </summary>
        public static string MessageEmfFunctionUnknown {
            get {
                return ResourceManager.GetString("MessageEmfFunctionUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while writing XAML. Details: ähnelt.
        /// </summary>
        public static string MessageXamlError {
            get {
                return ResourceManager.GetString("MessageXamlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die XAML for {0} not implemented yet ähnelt.
        /// </summary>
        public static string MessageXamlNotImplemented {
            get {
                return ResourceManager.GetString("MessageXamlNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die XAML for Path Data is not available due to Silverlight runtime limitations ähnelt.
        /// </summary>
        public static string MessageXamlPathDataNotSupported {
            get {
                return ResourceManager.GetString("MessageXamlPathDataNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die XAML truncated, reached the specified maximum number of {0} UI elements ähnelt.
        /// </summary>
        public static string MessageXamlTruncated {
            get {
                return ResourceManager.GetString("MessageXamlTruncated", resourceCulture);
            }
        }
    }
}
